### ISSUE TITLE
Je ne trouve plus le pointage de chaque CU ou FURPS

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-enonce-lab1#1]
Avant, il y a avait ça dans l'énoncé : https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/tree/a3292c9ea7d2009be63718324717658e7d5c78ad#grille-de-pointage-des-exigences

**Comment by fuhrmanator** [comment]
Tout ce qui concerne les points et les grilles de correction sont dans un chiffrier sur Google Drive.
