### ISSUE TITLE
Phrase maladroite sur "plus de points pour compenser..."

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-enonce-lab1#10]
Aussi, un phrase maladroite :

```
Vous pouvez implémenter plus de points pour compenser les pertes durant la correction mais la note maximale sera de 100%.

Pour les valeurs de d dépassant 100 %, le maximum est 110 %.
```

La première phrase parle du labo au complet (implémentation + conception). La deuxième phrase par uniquement de l'implémentation. Il faudrait que ça soit plus clair.

_Originally posted by @Olon11 in https://github.com/profcfuhrmanets/log210-enonce-lab1/issues/2#issuecomment-906675725_

**Comment by fuhrmanator** [comment]
Je crois que c'est @yvanross qui a écrit la phrase, alors je lui donne le Issue

**Comment by fuhrmanator** [comment]
J'ai supprimé la phrase dans #11 - à valider.

**Comment by Olon11** [comment]
C'est bon pour ce changement

**Comment by RubenLaden** [comment]
J'ai encore un doute car il semble y avoir deux informations différentes. En considérant qu'une équipe commence par sélectionner le minimum de CUs lui permettant d'obtenir exactement 100% (si son travail est "parfait"), elle peut :

1 - Choisir plus de CUs à chaque itération afin de compenser des pertes de points pendant la conception, et donc quand même avoir 100% à une itération malgré quelques erreurs.
2 - Obtenir des points bonus sur la dernière itération si elle implémenté plus de CUs que le minium initial, et donc compenser des pertes de points dans d'autres évaluations.

Peut-être que j'ai mal interpréter une des deux phrases, mais c'est de cette manière dont notre équipe avait été évaluée en tout cas.

**Comment by fuhrmanator** [comment]
> J'ai encore un doute car il semble y avoir deux informations différentes. En considérant qu'une équipe commence par sélectionner le minimum de CUs lui permettant d'obtenir exactement 100% (si son travail est "parfait"), elle peut :

Attention - réussir parfaitement le minimum n'est pas un travail parfait (dans le sens qu'on va avoir une bonne note à la fin). C'est pour ne pas avoir une pénalité de manque d'avancement. Par exemple, l'équipe peut avoir 100% pour la note `a`, 100% pour `b` et 100% pour `c`, mais si elle a fait le minimum chaque fois elle n'aura que 10 points au total. S'il s'agit d'une équipe à 4 personnes, ça ne suffit pas pour avoir 100% pour `d`, car ça prend 11 points au total. 

> 1 - Choisir plus de CUs à chaque itération afin de compenser des pertes de points pendant la conception, et donc quand même avoir 100% à une itération malgré quelques erreurs.

OK, je pense que c'est le sens éventuel de la phrase que Yvan avait écrite (que j'ai finalement supprimée dans #11), mais j'attends son feeback. Personnellement je trouve ce genre de stratégie tordue et bâclée et je voudrais éliminer les échappatoires à ce propos le cas échéant. Je préfère qu'une équipe se concentre sur un bon design plutôt que soumettre plus de choses incertaines, surtout que ça complique la correction quand c'est un travail éventuellement mal fait juste pour augmenter les points.

> 2 - Obtenir des points bonus sur la dernière itération si elle implémenté plus de CUs que le minium initial, et donc compenser des pertes de points dans d'autres évaluations.

Je ne suis pas sûr de comprends pas la phrase. La valeur de `d` n'est prise en compte qu'à la dernière itération. La valeur de `d` peut aller à 110%, ce qui peut effectivement ratrapper quelques points perdus dans les évaluations de la conception `a`, `b` et `c`.

> Peut-être que j'ai mal interpréter une des deux phrases, mais c'est de cette manière dont notre équipe avait été évaluée en tout cas.

Merci de poser la question! C'est sûr et certain qu'il y a eu des interprétations différentes de l'évaluation dans le passé. 

Ça fait des années que je propose des exemples concrets pour expliquer la correction -- c'est peut-être le temps :)

**Comment by RubenLaden** [comment]
>OK, je pense que c'est le sens éventuel de la phrase que Yvan avait écrite (que j'ai finalement supprimée dans #11), mais j'attends son feeback. Personnellement je trouve ce genre de stratégie tordue et bâclée et je voudrais éliminer les échappatoires à ce propos le cas échéant. Je préfère qu'une équipe se concentre sur un bon design plutôt que soumettre plus de choses incertaines, surtout que ça complique la correction quand c'est un travail éventuellement mal fait juste pour augmenter les points.

Je suis complètement d'accord !

>Je ne suis pas sûr de comprendre la phrase. La valeur de d n'est prise en compte qu'à la dernière itération. La valeur de d peut aller à 110%, ce qui peut effectivement ratrapper quelques points perdus dans les évaluations de la conception a, b et c.

Effectivement, et même des points perdus dans d'autres évaluations (intra par exemple) si tout le reste (conception, rapport, etc) des itérations est 100% aussi.
