### ISSUE TITLE
Incohérence entre la grille d'évaluation et les exigences

### ISSUE THREAD

**Issue by RubenLaden** [profcfuhrmanets/log210-enonce-lab1#12]
- Les exigences font mention d'un "CU01c - Retirer cours", mais la grille ne le contient pas :
  https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/README-exigences-client.md#cu01c---retirer-cours
 
- Les exigences contiennent un "CU02b - Récupérer question" qui n'est pas mentionné dans la grille non plus :
  https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/README-exigences-client.md#cu02b---r%C3%A9cup%C3%A9rer-question
 
- Les CU03 et CU04 sont inversés dans la grille.
 
- Dans la grille, CU04e devrait être CU04d (ou plus exactement CU03d selon le point précédent)

- Dans la grille, le CU06 est "Remettre devoir" alors que dans les exigences, c'est "Corriger questionnaire" :
  https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/README-exigences-client.md#cu06---corriger-questionnaire-correction-manuelle
  S'il devient "CU05e - Corriger questionnaire", c'est non seulement plus cohérent mais ça corrige aussi le décalage des CUs suivants

- "CU08 - Consulter mes notes" et "CU09 - Exporter les notes des étudiants" ne pointe vers aucun CU dans l'énoncé

**Comment by yvanross** [comment]
Je viens de vérifier les descriptions de chaque élément de la grille de correction et corriger les noms qui étaient différents par rapport aux exigences client.
