### ISSUE TITLE
Incohérence entre les différentes grilles de notations

### ISSUE THREAD

**Issue by RubenLaden** [profcfuhrmanets/log210-enonce-lab1#13]
Dans la section "Déroulement des itérations" de l'énoncé, le lien vers la grille de notation amène vers une feuille de calcul de plusieurs pages, contenant différentes grilles.

Plus bas dans l'énoncé, dans la section "Modalités d'évaluation", des liens vers d'autres grilles disponibles. Ces grilles individuelles  ressemblent beaucoup à toutes celles contenues dans la feuille de calcul mentionnée précédemment, mais ne sont pas identiques.

**Comment by fuhrmanator** [comment]
OK - je vais voir ça, mais normalement on a "publié" chaque onglet de la grille principale pour expliquer son contexte. Tout est censé être dans la même grille, mais il se peut qu'il y ait eu de la confusion entre Yvan et moi. Merci d'avoir signalé encore l'incohérence.

**Comment by fuhrmanator** [comment]
Au fait "ma version" de la grille est nommée : log210-template-notes-lab1-bcapg.xlsx et ça parait normalement en haut à gauche, p.ex.:

![image](https://user-images.githubusercontent.com/7606540/134396945-386cfb91-53d2-4460-9675-29ee50a20419.png)

**Comment by yvanross** [comment]
Il y avait des liens vers deux grilles de correction différentes dans le document.  Je viens de corriger le problème pour utiliser uniquement la grille de Christopher.
