### ISSUE TITLE
La correction interactive du rapport de l'itération 1 n'est plus dans la grille de correction

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-enonce-lab1#17]
Description de la correction interactive :
> À la deuxième semaine de l'itération 1, vous devrez présenter les artéfacts, l'implémentation et les tests des CU01a et CU01b à votre auxiliaire d'enseignement. Vous recevrez des commentaires pour vous aider avant la remise de votre premier rapport et de votre première démo. Cette activité est informelle, mais votre participation est notée et obligatoire.

La grille de correction ne contient plus de note pour cette activité. A-t-elle été retirée? Si c'est le cas, c'est dommage, puisqu'il s'agissait d'une bonne opportunité d'apprentissage pour les étudiants. On pouvait clarifier certaines incompréhensions et répondre à leurs questions en lien avec la conception et l'implémentation et les guider vers la bonne direction. L'activité les aidait à appliquer le processus de LOG210 plus rapidement et à réduire le temps passé sur le laboratoire (moins de refactorisation).

**Comment by yvanross** [comment]
Ajout de la section Vérification RDCU pour les rapports préliminaires dans chacun des rapport.
