### ISSUE TITLE
Guide de correction

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab1#19]
Ajouter un guide de correction pour les chargés de laboratoire

**Comment by fuhrmanator** [comment]
Bonne idée -- @Olon11 avait déjà commencé de quoi dans un Google Doc. Le repo étant publique, devrions-nous plutôt mettre ce guide dans un espace restreint?

**Comment by Olon11** [comment]
Parles-tu du guide de correction dans l'énoncé? Ou de celui du laboratoire 0? Ou de la grille de correction détaillée?

**Comment by yvanross** [comment]
On a ajouté une colonne problèmes identifiés dans chaque page de la grille de correction.  Il faudrait trouver une mécanique pour simplement avoir a choisir des réponses à partir d'une sélection qui pourrait être mise à jours dans une fichier excel.
