### ISSUE TITLE
Incohérence avec les pointages pour chaque itération.

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-enonce-lab1#2]
Dans Déroulement des itérations, ça dit :

```
Chaque itération nécessite un avancement (évolution) sur le plan des exigences par une valeur minimale indiquée.

Itération 1 - 3 points
Itération 2 - 3 points supplémentaires
Itération 3 - 4 points supplémentaires`
```

Dans Processus d'évaluation des laboratoires, ça dit :

```
Le nombre de points minimal requis pour une note de 100% correspond au tableau suivant:

Nombre d'étudiant | NbPoints
3                              | 8.25
4                              | 11.00
5                              | 13.75
6                              | 16.50
```

**Comment by fuhrmanator** [comment]
> Dans Déroulement des itérations, ça dit :
> 
> ```
> Chaque itération nécessite un avancement (évolution) sur le plan des exigences par une valeur minimale indiquée.
> 
> Itération 1 - 3 points
> Itération 2 - 3 points supplémentaires
> Itération 3 - 4 points supplémentaires`
> ```
> 
> Dans Processus d'évaluation des laboratoires, ça dit :
> 
> ```
> Le nombre de points minimal requis pour une note de 100% correspond au tableau suivant:
> 
> Nombre d'étudiant | NbPoints
> 3                              | 8.25
> 4                              | 11.00
> 5                              | 13.75
> 6                              | 16.50
> ```

Tu spécifies une incohérence dans le titre, mais c'est vague dans le texte. 

Je dois deviner que tu penses qu'on devrait diminuer le nombre de points par itération s'il y a moins que 5 membres dans une équipe?

**Comment by fuhrmanator** [comment]
> La première phrase parle du labo au complet (implémentation + conception). La deuxième phrase par[le] uniquement de l'implémentation. Il faudrait que ça soit plus clair.

Je crée un issue à part, car c'est indépendant du premier.

**Comment by Olon11** [comment]
Pour le premier commentaire, l'incohérence, c'est le nombre de points qu'on demande d'atteindre. Dans la première section, c'est 11 pour tout le monde. Dans la deuxième section, ça dépend du nombre de personnes dans l'équipe.

**Comment by fuhrmanator** [comment]
Ok, ça finit par être 11, mais la première partie est un guide pour le minimum. La deuxième est pour calculer la note. Respecter le minimum à chaque itération permet d'éviter la pénalité sur le manque d'avancement, mais n'est pas suffisant pour avoir 100% surtout s'il y a plus de 4 coéquipiers.

On peut ajouter une phrase pour communiquer ça, puis aussi une souplesse (à la discrétion de l'auxiliaire) sur le minimum pour les équipes ayant moins de 4 .

**Comment by RubenLaden** [comment]
Je dois dire que ce n'est toujours pas très clair, même avec les explications supplémentaires. Imaginons deux équipes, une de 3 membres et une de 5 membres, qui font "parfaitement" le travail. Est-ce que l'équipe de 3 personnes aura 2.75 points de trop (11 - 8.35) ?  Et l'équipe de 5 aura un déficit de 2.75 points (11 - 13.75) ?
Si le réel pointage est celui pondéré par la taille de l'équipe, alors la première indication est assez mélangeante. Il faudrait soit la retirer, soit la déplacer et l'utiliser comme exemple "type pour une équipe de 4" dans la partie contenant le pointage pondéré.

Si vous validez, je soumettrai une PR pour rectifier ça. C'est aussi quelque chose que l'on devra clarifier avec les étudiants car c'est assez important et ce n'est pas les directives qu'on leur a donné.

**Comment by fuhrmanator** [comment]
> Imaginons deux équipes, une de 3 membres et une de 5 membres, qui font "parfaitement" le travail

"Parfaitement" voudrait dire qu'ils ont réalisé [toutes les fonctionnalités](https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/README-exigences-client.md#survol-des-fonctionnalit%C3%A9s) et les exigences URPS. 
Ça serait la somme de tous les points dans la [grille](https://docs.google.com/spreadsheets/d/e/2PACX-1vSv41don0mUrXlng6Uk46yrKrKPZ1P4jbDLBi6qEO0s3pybZ93uAwBlkKqG6HD6AA/pubhtml?gid=1269446979&single=true) qui dépasse 30 points je crois.

**Comment by fuhrmanator** [comment]
@RubenLaden on a dû mettre un minimum par itération, sinon des équipes n'avançaient pas suffisamment. Elles pouvaient juste faire un cas d'utilisation à la première et à la 2e itération, puis elles essayaient de faire une grosse 3e itération super risquée.

La pénalité est indiquée dans la même grille (actuelle 10% si le minimum n'a pas été respecté).

**Comment by fuhrmanator** [comment]
> Si vous validez, je soumettrai une PR pour rectifier ça. C'est aussi quelque chose que l'on devra clarifier avec les étudiants car c'est assez important et ce n'est pas les directives qu'on leur a donné.

Je vais discuter de vive voix avec @yvanross pour clarifier le tout aujourd'hui si possible et je proposerai une PR.

**Comment by RubenLaden** [comment]
En fait, quand je disais « [faire] "parfaitement" le travail», je faisais simplement reférence au travail minimum donnant 11. Je vais reformuler ma question : Si une équipe de 3 personnes implémente "parfaitement" le minimum de CUs donnant 11 points, elle aura un peu trop travaillé (2.75 points de travail en trop). De même, une équipe de 5 qui implémente "parfaitement" aussi ces mêmes CUs, toujours pour un total de 11 points, n'aura pas assez travaillé (manque de 2.75 points de travail) ?

**Comment by RubenLaden** [comment]
> 
> 
> @RubenLaden on a dû mettre un minimum par itération, sinon des équipes n'avançaient pas suffisamment. Elles pouvaient juste faire un cas d'utilisation à la première et à la 2e itération, puis elles essayaient de faire une grosse 3e itération super risquée.
> 
> La pénalité est indiquée dans la même grille (actuellement c'est 10% si le minimum n'a pas été respecté).

Je comprends tout à fait, c'est même une très bonne chose, le problème c'est que le minimum n'est pas cohérent avec le pointage pondéré par taille d'équipe. Si il faut, pour une équipe de 3, un total de 8.25 points pour avoir 100%, mais que cette équipe doit implémenter un minimum de : 3 points (itération 1) + 3 points (itération 2) + 4 points (itération 3), alors on leur demande de travailler plus que nécessaire. Pire que ça, on leur demande de travailler autant qu'une équipe de 4.

Cependant, ce n'est pas un problème pour les équipes de 4 et plus car là ça devient leur responsabilité de choisir plus de CUs s'ils veulent avoir 100%

**Comment by fuhrmanator** [comment]
>  alors on leur demande de travailler quasi autant qu'une équipe de 4.

Dans https://github.com/profcfuhrmanets/log210-enonce-lab1/issues/2#issuecomment-924214272 j'avais écrit:

> On peut ajouter une phrase pour communiquer ça, puis aussi une souplesse (à la discrétion de l'auxiliaire) sur le minimum pour les équipes ayant moins de 4 .

**Comment by RubenLaden** [comment]
Effectivement, au temps pour moi. Merci !
