### ISSUE TITLE
Rééquilibrage du pointage des CUs

### ISSUE THREAD

**Issue by RubenLaden** [profcfuhrmanets/log210-enonce-lab1#23]
Pour faire suite aux suggestions de certaines équipes visant à augmenter le pointage des CU04 et CU07, je propose de revoir le pointage de la plupart des CUs pour les sessions suivantes.

- CU01b, CU02b, CU03b : 1 -> 0.5 (Les récupérations sont assez simples à gérer)
- CU01c, CU02d, CU03c, CU05d : 1 -> 0.5 ou 0.25 (les suppressions sont très faciles à gérer)
- CU02a - Support question type mise en correspondance : 0.5 -> 1.5 ou 1.25 (car la vue est bien plus compliquée à faire que vrai/faux, réponse courte ou numérique)
- CU02a - Support question type choix multiples : 0.5 -> 1 ou 0.75 (ici aussi la vue est plus compliquée que vrai/faux, réponse courte ou numérique)
- CU02c - 1 + points bonus selon les types de questions sélectionnés (sinon ce CU vaut autant de points qu'on ait 1 seul ou tous les types de questions)
- CU03a : 2 -> 1.5 ou 1 (plutôt facile, la complexité arrive surtout avec CU04 et CU07)
- CU04 : 1 -> 2 ou 1.75 (relativement demandant)
- CU05b : 1 -> 0.75 ou 0.5 (assez facile et quasi obligatoire pour démontrer CU05a)
- CU07 : 1 -> 2 (relativement demandant)
- CU08 : 2 -> 2 + points bonus selon les types de questions intégrés (ce CU est relativement demandant, surtout si on veut intégrer tous les types de questions)
- S2 : 2 -> 1 ou 0.75 (avec un minium de connaissances ou de recherches ce FURPS peut être facilement réalisé, ce sont presque des points gratuits)
- U1 : 0.25 -> 2? ou 3? ou 4? (Ce FURPS peut vite demander un travail colossal pour être correctement réalisé et il se complexifie à chaque itération. Puisque la vue s'enrichie à chaque itération, choisir ce FURPS à l'itération 3 est bien plus demandant qu'à l'itération 1. Il devrait pouvoir être sélectionné à chaque itération. Sa pondération devrait croître à chaque itération pour les équipes ne l'ayant pas encore sélectionné et rester le même pour les équipes qui l'avaient déjà sélectionné)

Les nouvelles valeurs numériques que je propose peuvent être encore raffinées, c'est surtout l'augmentation/diminution qui importe.

Edit : Ajout de suggestion pour CU02c

**Comment by fuhrmanator** [comment]
Merci pour cette info @RubenLaden.

**Comment by Olon11** [comment]
Pour S2, les étudiants n'ont rien à faire. Le script est déjà écrit. Je l'enlèverais complètement.

**Comment by RubenLaden** [comment]
> Pour S2, les étudiants n'ont rien à faire. Le script est déjà écrit. Je l'enlèverais complètement.

C'est vrai que la configuration de Github actions est déjà présente, mais je n'ai encore pas vu de build fonctionner correctement. Il me semble que le but de S2 à la base était d'utiliser un système externe (style `Travis-CI`) pour exécuter les tests. Au lieu de retirer S2, on pourrait simplement retirer la configuration de Github actions, non ?

**Comment by RubenLaden** [comment]
Aussi, j'ai mis à jour la description pour inclure une suggestion sur CU02c, dont la charge de travail augmente avec le nombre de types de questions, sans que sa pondération n'augmente pour autant. Merci à Cynthia Cahill de l'équipe 4 du groupe 1 pour avoir relevé le problème.

**Comment by Olon11** [comment]
Le build ne fonctionne pas, car il y a trop d'équipes pour la quantité de minutes de build qu'on a (2000 minutes par mois). Les minutes sont utilisées en quelques heures seulement. Si on retire le script, on perd une vérification utile lorsqu'on fait des mises à jour sur le squelette.

Travis CI, c'est l'ancien système d'intégration continue. Il ne devrait plus y avoir de référence à cet outil.

**Comment by yvanross** [comment]
Github action enlevé.  Référence à travis enlevé.
