### ISSUE TITLE
Ajouter un nouveau CU pour la connexion (Étudiant vs Enseignant) ?

### ISSUE THREAD

**Issue by RubenLaden** [profcfuhrmanets/log210-enonce-lab1#24]
La partie connexion du laboratoire est nécessaire, mais implicite, et il n'est pas forcément très clair si les étudiants doivent pouvoir se connecter à SGA dès les premiers CU ou seulement après CU07/CU08. Comme Élaine l'a suggéré, il serait intéressant d'avoir un CU dédié à la connexion (pour quelque chose comme 0.5 ou 1 point).

Cela impliquerait les changements suivants :
- Ajouter ce nouveau CU à liste des exigences clients.
- Ajouter ce nouveau CU à la grille de d'évaluation partie "implémentation".
- Mettre à jour l'énoncé pour inclure ce nouveau CU comme un CU obligatoire.

**Comment by fuhrmanator** [comment]
J'aime cette suggestion. Merci @RubenLaden et Élaine. En effet, la connexion doit être faite pour chaque acteur et les fonctionnalités visibles sont différentes. 

Par contre, je n'aime pas trop l'idée que ça rapporte des points, car une connexion n'ajoute pas de valeur dans un logiciel. J'ai vu plusieurs PFE où toute une équipe de quatre personnes bosse pendant 3 semaines et tout ce qui fonctionne est la connexion. Le feedback du client sur une telle itération est presque zéro.

Larman mentionne comme heuristique le "test du patron" pour juger si un cas d'utilisation ajoute de la valeur. Si tu dis à ton patron que tu t'es connecté au système 50 fois dans une journée, tu n'as rien fait réellement. Mais corriger 50 devoirs, c'est de la valeur.

**Comment by RubenLaden** [comment]
> une connexion n'ajoute pas de valeur dans un logiciel.

Je ne suis pas forcément d'accord, notamment dans le cas de ce laboratoire. La connexion s'accompagne de mécanismes d'authentification (récupération et gestion du token) et d'autorisation (permissions étudiants vs permissions enseignant), ce qui a pour but de sécuriser le logiciel et de permettre à plusieurs utilisateurs d'être connectés en même temps. Je pense que ces deux choses ont de la valeur.

Puisqu'il n'y a pas de requis explicites pour la gestion de la connexion, certaines équipes ne supportent qu'une seule connexion (ou session) à la fois.

> Mais corriger 50 devoirs, c'est de la valeur.

C'est un autre problème, qui mérite sa propre "issue", mais puisque les équipes sont libres de choisir leurs CUs (après les CU1a et CU1b obligatoires), il arrive souvent que leur application ne soit pas très cohérente. Ces équipes peuvent ajouter et/ou modifier et/ou supprimer des cours, des questions, des devoirs et des questionnaires et obtiennent tous les points dont elles ont besoin. Seulement, on ne peut rien en faire puisqu'on ne peut pas passer un questionnaire ou remettre de devoir. Je trouve qu'ajouter 50 questions sans questionnaires n'a pas beaucoup de valeur, de même qu'ajouter 50 questionnaires sans étudiants pour les utiliser.

**Comment by fuhrmanator** [comment]
> une connexion [toute seule] n'ajoute pas de valeur dans un logiciel.

Mon point est qu'elle n'a pas de valeur sans autre CUs qui en dépendent. Donc, si on met une condition sur le pointage que ça compte seulement si d'autres fonctions sont réalisées qui en dépendent, c'est mieux.

**Comment by Olon11** [comment]
Un autre élément à considérer est que le login ne demande pas d'appliquer la méthode d'analyse et de conception présentée dans le cours. Ça n'aide pas à atteindre les objectifs du laboratoire

**Comment by RubenLaden** [comment]
> Mon point est qu'elle n'a pas de valeur sans autre CUs qui en dépendent. Donc, si on met une condition sur le pointage que ça compte seulement si d'autres fonctions sont réalisées qui en dépendent, c'est mieux.

L'idée du pointage conditionnel est intéressante (pour ce CU ou un autre), mais si on rend ce CU obligatoire, il n'y aurait pas vraiment besoin de le rendre conditionnel, à moins qu'on craigne qu'un équipe ne fasse que ce CU pour tout le laboratoire.

> Un autre élément à considérer est que le login ne demande pas d'appliquer la méthode d'analyse et de conception présentée dans le cours. Ça n'aide pas à atteindre les objectifs du laboratoire

Comment ça ? Ce CU possède des acteurs, implique une communication avec SGB et altère l'état de SGA. Je verrai tout à fait un DSS, un contrat et un RDCU associés cette nouvelle opération. Peut-être que je vois ça de manière trop simpliste

**Comment by elainesoucy** [comment]
Si un CU pour le login est ajouté, il faudrait alors qu'il  y ait le DSS, RDCU et contrats associés. Présentement, les équipes ne font pas d'artéfacts pour le login et je ne vois pas vraiment l'utilité d'ajouter des artéfacts pour représenter cette partie du laboratoire. Je crois plutôt que je le mettrais en conditions au tout début : les login Enseignant et Etudiant doivent être réalisés, mais aucun artéfact à faire pour ceux-ci et ils seraient obligatoires (sans point, car pas d'artéfacts). Il pourrait être intéressant de mentionner dans cette condition ce qu'engendre la connexion Enseignant vs Etudiant.

**Comment by Olon11** [comment]
> Comment ça ? Ce CU possède des acteurs, implique une communication avec SGB et altère l'état de SGA. Je verrai tout à fait un DSS, un contrat et un RDCU associés cette nouvelle opération. Peut-être que je vois ça de manière trop simpliste

La connexion ne fait pas partie du domaine de l'application. C'est un élément technique. Les artéfacts visent à modéliser le domaine. Même s'il y a une modification de l'état du SGA, ce n'est pas une modification en lien avec le domaine. Même chose pour les RDCU. Il y a un comportement à modéliser, mais il ne fait pas interagir les éléments du domaine.

**Comment by fuhrmanator** [comment]
@Olon11 en effet, une connexion est un détail informatique qui ne devrait pas avoir une classe dans le MDD. Alors un DSS, une RDCU ou des contrats ne seraient pas intéressants. C'est cohérent avec le test du patron, car l'évolution de l'état du MDD suit le modèle d'affaires (chose importante a priori pour un patron).

**Comment by yvanross** [comment]
voici ce que j'ai ajouté dans la section cas d'utilisation du document d'exigence.

La majorité des cas d'utilisation ont une précondition d'authentification pour un enseignant ou un étudiant. La connexion d'un enseignant ou d'un étudiant s'accompagne de mécanismes d'authentification (récupération et gestion du token) et d'autorisation (permissions étudiants vs permissions enseignant), ce qui a pour but de sécuriser le logiciel et de permettre à plusieurs utilisateurs d'être connectés en même temps. Vous devez donc réaliser la mécanique d'authentification au plus tard durant la seconde itération.
