### ISSUE TITLE
Écrire dans les exigences d'un CU qu'il dépend d'un autre

### ISSUE THREAD

**Issue by elainesoucy** [profcfuhrmanets/log210-enonce-lab1#27]
Pour faciliter le flot d'exécution, je propose d'écrire dans les exigences du CU04 - Corriger devoir, que le CU07 - Remettre devoir ait été préalablement réalisé. Selon ma compréhension, pour corriger un devoir, il faut que des devoirs soient présents. Je crois donc qu'il serait logique que le CU07 - Remettre devoir soit réalisé avant le CU04.

De même pour la partie des questionnaires, je crois qu'il pourrait être intéressant d'ajouter explicitement dans l'énoncé que CU08 - Passer questionnaire soit fait préalablement au CU06 - Corriger questionnaire.

**Comment by Olon11** [comment]
Je crois que la sélection intelligente des CUs est la responsabilité de l'équipe. Ce serait mieux d'indiquer dans l'énoncé qu'un CU qui n'est pas complet (parce qu'un CU sur lequel il dépend n'a pas été réalisé) ne sera pas corrigé

**Comment by Olon11** [comment]
Je changerais le nom de l'issue pour qu'il soit plus clair. Tu peux toujours utiliser le flair enhancement pour montrer que c'est une suggestion

**Comment by elainesoucy** [comment]
Je crois également que c'est la responsabilité de l'équipe, mais en discutant avec plusieurs d'entre elles je me suis rendue compte que celles-ci ne font pas une sélection intelligente malgré que je l'ai souligné à quelques reprises dans le cours.

**Comment by fuhrmanator** [comment]
Je pense qu'on peut régler ce problème avec les scénarios de tests plus explicites, comme j'explique dans #30. Par exemple, pour avoir tous les points pour *Corriger devoir*, il doit fonctionner dans un scénario de test complet:
- ÉtudiantA remet devoir X
- EnsB corrige devoir X
- EtudiantA voit que son devoir X a été corrigé (changement d'état)

Il faudra détailler plus les scénarios afin qu'ils soient réalisables dans Jest.

Je crois aussi que ça peut faciliter la correction d'un CU.

**Comment by yvanross** [comment]
Enlever la colonne préalable et ajouter des tests correspondant à ces cas.

**Comment by fuhrmanator** [comment]
J'ai pensé à une autre idée basée sur le concept de MVP. À la dernière itération, si j'ai une fonctionnalité **Ajouter question**, mais elle ne sert à rien (un étudiant ne peut pas passer un quiz), la fonctionnalité ne sert à rien.

CU04 Corriger devoir et CU06 Corriger questionnaire sont (selon moi) les deux CU qui importent le plus.

![image](https://user-images.githubusercontent.com/7606540/147710602-bb646704-edec-48d9-a973-abc718b7e096.png)

On devrait donc favoriser les points en fonction de ces objectifs. 

Je peux voir au moins deux chemins minimalistes qui sont dans l'esprit d'un MVP:
- Créer/Récupérer cours + Créer/Récupérer devoir + Remettre devoir + Corriger devoir (sans modifier/supprimer de cours/devoir)
- Créer/Récupérer cours + Créer/Récupérer question + Créer/Récupérer question + Passer questionnaire + Corriger questionnaire (sans modifier/supprimer de cours/question/questionnaire en supportant que des questions de type vrai-faux)

Si on pousse les équipes à faire de quoi qui a une vraie valeur, une équipe n'ayant pas atteint l'objectif CU04 ou CU06 ne devrait pas avoir 100% et surtout pas de points boni.

Qu'en pensez-vous?

**Comment by Olon11** [comment]
L'idée du MVP est bonne, mais je crois que du point de vue du client, le fait de pouvoir modifier ou supprimer une ressource est essentiel.

**Comment by fuhrmanator** [comment]
Voici un graphe des dépendances. Ça définit les préalables pour avoir des points:

![DependanceCasUtilisations](https://www.plantuml.com/plantuml/svg/ZP9DQiCm48NtEeN8fgj24yU9mRW47EYs5B8AMIZMn1QCfLII0oNaG3b7BbPLbckrpQ82CGnyxsb-j3AMQTkrIDTm1CcPhA1aPcC52iEiKD8GBchDZWqzA4NFXBg3R0zOJDQtww0nbBjRCHSVkb4yoPrAMibQA1h04rXHCMyX5GUwDVO3eJW8HE0ETR5Ig7I1ecxi7Zkufz_btg7SF4tfDfJYavVRLOEcbUgqcUm6Q1P3im5wxy3uzaOmYS5a03cSb8ZzvZ4sfwNIMjJVuCYbCPV-VbSoeI5oNSJqOdJzmGVy7xEhDO0S1xMCtPVq3LgmLiEVchEOo-WhC-Pk3Rxpn-VUkez9Ji8K-tnAGbzzceMO1Ypzoi_z4lrUBYHiQv1VoCfzBlSrFm40 "DependanceCasUtilisations")

p.ex. pour avoir des points pour CU04, tous les préalables doivent être réalisés (tests qui passent).

Ça nous permet également d'expérimenter avec les pointage, on peut facilement mettre cette structure dans un chiffrier.
