### ISSUE TITLE
Étapes/détails manquants pour certains CUs

### ISSUE THREAD

**Issue by RubenLaden** [profcfuhrmanets/log210-enonce-lab1#28]
**CU03a - Ajouter devoir :**
- Il manque l'extension gérant le cas où un devoir avec le même nom existe déjà

**CU03c - Modifier devoir :**
- Il manque l'extension gérant le cas où le nouveau nom est déjà utilisé par un autre devoir

**CU05a - Ajouter questionnaire :**
- Étape 5. L'enseignant crée un nouveau questionnaire [...] 
  L'enseignant devrait aussi donne un nom à son questionnaire, pour l'identifier plus facilement.
- Ajouter l'extension gérant le cas où le nom est déjà utilisé par un autre questionnaire

**CU05c - Modifier questionnaire :**
- étape 3. L'enseignant modifie la description [...]
  L'enseignant devrait aussi pouvoir modifier le nom du questionnaire
- Ajouter l'extension gérant le cas où le nouveau nom est déjà utilisé par un autre questionnaire

**Comment by RubenLaden** [comment]
Si ces suggestions sont validées, je soumettrai une PR pour les intégrer

**Comment by yvanross** [comment]
j'ai ajouté les informations pour démontrer ces aspect avec à l'aide de test supplémentaire que les étudiants auront à réaliser.
