### ISSUE TITLE
Scénario de tests plus complexes (fonctionnalités interdépendantes)

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-enonce-lab1#30]
@RubenLaden a écrit
> C'est un autre problème, qui mérite sa propre "issue", mais puisque les équipes sont libres de choisir leurs CUs (après les CU1a et CU1b obligatoires), il arrive souvent que leur application ne soit pas très cohérente. Ces équipes peuvent ajouter et/ou modifier et/ou supprimer des cours, des questions, des devoirs et des questionnaires et obtiennent tous les points dont elles ont besoin. Seulement, on ne peut rien en faire puisqu'on ne peut pas passer un questionnaire ou remettre de devoir. Je trouve qu'ajouter 50 questions sans questionnaires n'a pas beaucoup de valeur, de même qu'ajouter 50 questionnaires sans étudiants pour les utiliser.

J'ai vu un cas bizarre dans le passé où un enseignant pouvait créer un questionnaire, mais le questionnaire apparaissait dans tous les cours. 

Les scénarios de tests devraient aller plus loin que le scénario de base du cas d'utilisation, et on peut les spécifier dans le document d'exigences. 

On peut essayer de résoudre le problème pour les cas qu'on connait pour l'instant.

**Comment by Olon11** [comment]
Dans ton exemple, je ne vois pas comment faire pour éviter ce problème avec les tests? C'est plutôt une erreur dans la compréhension des exigences que dans les tests. À la correction interactive, l'équipe a probablement reçu un commentaire d'un chargé en lien avec cette erreur. Par la suite, ils ont dû corrigé le problème et mis à jour leurs tests.

**Comment by fuhrmanator** [comment]
Il suffit de faire des tests additionnels (un autre enseignant qui se connecte et qui ne voit pas les mêmes cours, les mêmes choses créés dans le premier test). Exemple:

- EnsA crée cours X
- EnsA voit cours X dans sa liste
- EnsB ne voit pas cours dans sa liste X

Pour les cas mentionnés par @RubenLaden, ça serait 
- EnsA crée questionnaire X
- EnsA voit questionnaire X dans sa liste
- ÉtudiantJ (qui est dans le cours où X a été créé) voit X dans la liste, ainsi que des questions dans X

Un questionnaire sans questions ou qui n'est pas visible par tous les acteurs ne devrait pas valoir des points.

**Comment by yvanross** [comment]
J'ai ajouté des tests à réaliser pour chaque CU
