### ISSUE TITLE
Résponses aux question des étudiants

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab1#37]
Question en dehors des périodes de laboratoire.  Quel est la politique?

Avec discord, il y a de plus en plus de question auxquels les chargés de laboratoire doivent répondre en dehors des heures de laboratoire.

Cela devient problèmatique surtout quand les étudiants ne se présentent pas aux laboratoire et pose plusieurs questions en dehors de celui-ci.

Comment on gère ça!!!!

**Comment by fuhrmanator** [comment]
Je dirais qu'il faut être raisonnable. Les auxiliaires peuvent définir et communiquer leur politique pour répondre aux questions. Ils ne sont pas obligés de répondre au questions sur discord en tout temps. Politique simple: répondre immédiatement aux questions lors des séances de lab mais pas de garantie en dehors de la période. 

Personnellement je désactive les notifications quand je dois bosser sur un truc important. Les auxiliaires ont le droit de faire la même chose.

**Comment by yvanross** [comment]
ajouter dans le guide des chargés de laboratoire https://docs.google.com/document/d/178ROie5TS3vF3bqOIyyyFRvo9QUuCTgVInX6YUe7yLc/edit?usp=sharing
