### ISSUE TITLE
LINTER

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab1#38]
- linter:  sonarLint pour lab0 et lab1

**Comment by fuhrmanator** [comment]
Y a-t-il un moyen de faire la même chose avec une extension VSC. Pour simplifier la config de l'environnement et la documentation des labs. On a supprimé l'outil de build et on fait tout avec tsc pour cette raison.

**Comment by yvanross** [comment]
Mettre en mode facultatif avec tech debt metric

**Comment by yvanross** [comment]
ajouter dans les directives d'implémentation
