### ISSUE TITLE
Faire en sorte que la grille (note) soit cohérente avec les indicateurs BCAPG

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-enonce-lab1#4]
SIGNETS définit des indicateurs et leurs mesures proviennent des labos - la grille dans les rapports devrait être cohérente afin que les chargés puissent saisir (dans le chiffrier exporté de SIGNETS) les valeurs qui correspondent aux sous-éléments du lab 1, 2, 3, etc.

![image](https://user-images.githubusercontent.com/7606540/104071525-57ee8500-51d7-11eb-8b3b-b53e6e3ec0ce.png)

**Comment by fuhrmanator** [comment]
@yvanross Désolé d'être insistant sur ce point, mais si les étudiants mettent tous les issues dans GitHub (à la place de compléter un plan), la validation pour les qualités du BCAPG sera très difficile voire impossible. Y a-t-il une autre raison que tu changes cette directive? On s'était entendu sur la grille de correction pour le BCAPG et sans plan "statique" ce n'est pas cohérent.

Je crois que ma directive a été modifiée (encore) dans ce changement:
https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/0f80f135bc55196edda01cf9bd40faeed2916f73/rapports/plan-it%C3%A9ration-exemple.md

**Comment by fuhrmanator** [comment]
Pour renforcer la cohérence, je rappelle que les grilles vont toutes se trouver dans le chiffrier (Google ou autre) qui est lisible par les étudiants et utilisable par les auxiliaires.

**Comment by yvanross** [comment]
Le plan d'itération est statique et tu as ajouté les indicateurs dans le templates.  Est-ce qu'il reste autre chose à faire?
