### ISSUE TITLE
GIFT

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab1#40]
- GIFT ne contient pas de rétroaction pour les réponses bonnes et mauvaises. L’interface doit impérativement implémenter la section rétroaction

**Comment by fuhrmanator** [comment]
Si, la rétroaction fait partie de GIFT. Le caractère # dans une réponse.

**Comment by yvanross** [comment]
https://github.com/fuhrmanator/GIFT-grammar-PEG.js/blob/master/tests/questions/TFTwoFeedback.gift

**Comment by yvanross** [comment]
Ajouté dans les exigences
