### ISSUE TITLE
Le système affiche 

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab1#45]
- Mention de "le système affiche" alors qu'il n'affiche rien du tout, il retourne des valeurs. Sauf si on considère deux systèmes, le navigateur et SGA. Modifier l'énoncé pour changer cette utilisation de "Système" ? (le navigateur affiche ... le système retourne ...)
Spécifier que le navigateur affiche l’information

**Comment by fuhrmanator** [comment]
Mais un use case est la perspective d'un acteur. Le système et une abstraction de la solution. C'est expliqué dans le chapitre sur les use cases.

**Comment by fuhrmanator** [comment]
Ne pas changer dans les cas d'utilisation. Le texte est censé être indépendant de la technologie.
