### ISSUE TITLE
Préconditions dans les contrats

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab1#46]
Je suggère de toujours demander les préconditions dans les contrats. Il y a toujours des préconditions nécessaires pour la réalisation de certaines post-condition. Les étudiants doivent réaliser d'ou viennent ces préconditions. Ils devront coder celle-ci.

**Comment by fuhrmanator** [comment]
Je ne suis pas contre l'idée. Dans les notes de cours je les déconseille puisque la théorie ne donne aucune directive là-dessus et je n'avais pas le temps de créer les directives qui risquent d'être incohérentes. En plus, les contrats étant facultatifs, c'est une distraction pour le cours, je trouve. Cela dit, si tu as une référence pour les directives à donner, ça serait bien. Sinon, on aura n'importe quoi comme preconditions et c'est difficile de faire une correction. Ce problème existe depuis LOG220. en fait ...

**Comment by yvanross** [comment]
Identifié comme facultatif
