### ISSUE TITLE
CU02a clarifier choix essai 

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab1#49]
Il faut clarifier quel est le type de question correspondant à choix essai
https://docs.google.com/spreadsheets/d/e/2PACX-1vSv41don0mUrXlng6Uk46yrKrKPZ1P4jbDLBi6qEO0s3pybZ93uAwBlkKqG6HD6AA/pubhtml?gid=1269446979&single=true

**Comment by yvanross** [comment]
@fuhrmanator est-ce que tu as une idée à quoi correspond ce type de question?

**Comment by fuhrmanator** [comment]
Choix essai est sûrement le type "Essay" (en anglais) ou le type de question à réponse longue (qui ne peut pas être corrigé automatiquement). 
![image](https://user-images.githubusercontent.com/7606540/147840157-2ef4eb22-bc4d-4319-ab31-8d40c0ab3815.png)

**Comment by fuhrmanator** [comment]
C'est le type de question qui nécessite le CU06 Corriger questionnaire

**Comment by fuhrmanator** [comment]
@yvanross je pense que tu as assez d'information pour fermer ceci?
