### ISSUE TITLE
Donner des astuces pour réaliser les pages web complexes

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-enonce-lab1#5]
Afin de minimiser l'effort passé sur certains views (l'aspect développement web qui est hors du cours), on peut donner des trucs et astuces pour réaliser les interfaces plus complexes. 

P.ex. un étudiant de mon groupe m'a dit qu'ils ont passé beaucoup de temps pour trouver une solution conviviale à sélectionner la liste de questions à mettre dans un questionnaire et que finalement ils ont utilisé Ajax dans un PUG avec les checkbox (sûrement pas la seule façon de faire). 

Je pense que ça serait raisonnable de fournir des astuces dans l'énoncé (pas forcément du code, mais au moins une approche avec lien vers un tutoriel ou une réponse sur StackOverflow, etc.).

**Comment by yvanross** [comment]
@fuhrmanator Est-ce qu'on pourrait couvrir ca dans le lab0?

**Comment by fuhrmanator** [comment]
Justement, je pensais faire un genre de barre de navigation en Pug (Angular supporte ça). 

@yvanross @Olon11 Avez-vous vu de bonnes solutions dans les réalisations faites par les équipes à date?

Sinon, une recherche Google avec navbar et pug donne plein d'exemples. La question est de savoir si ça fonctionne bien avec la complexité du projet. 

https://www.mockplus.com/blog/post/bootstrap-navbar-template
https://riemke.net/blog/bootstrap-with-pug-template/

Je veux bien faire qqch comme ça pour le lab0.

**Comment by fuhrmanator** [comment]
J'ai trouvé au moins une équipe qui a fait un beau design avec une navbar dans Pug, pour l'acteur Étudiant et Enseignant. Une recherche GitHub trouve vite les solutions dans l'organisation de Classroom. 

Le lab0 peut faire la même chose (plus simple), mais ça veut dire que je changerai le squelette pour avoir ce genre de design.

**Comment by fuhrmanator** [comment]
La barre de navigation avec Pug et Bootstrap dans le nouveau squelette devrait aider.
