### ISSUE TITLE
Demande changement d'équipe

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab1#53]
Autoriser un changement d'équipe si: 3 équipier qui ne font rien et un coéquipier qui veut travailler...

**Comment by fuhrmanator** [comment]
Si tu veux proposer une politique, il faut qu'elle soit cohérente avec [les conseils du lab0](https://docs.google.com/document/d/e/2PACX-1vRWTtdcGjUg34gqB6CW_EMt0H28Cgunq09_7HxMUoTLGERjUcQXBHlrYyB76PYJGjtaoYJhhsHS1Tjj/pub). 

Par exemple, la personne voulant changer d'équipe doit avoir "reflété au parasite son comportement dysfonctionnel" et doit en avoir une preuve de cette communication. Ça veut dire qu'un changement d'équipe ne pourrait pas se faire normalement avant la première itération, car ça prend du temps pour identifier et agir quand il y a un problème. Exceptions - personne d'autre dans l'équipe ne se pointe aux premières séances de lab, silence radio, etc. Un changement serait permis dans un cas comme ça, mais il faut une preuve de silence ou d'absence.

La politique doit tenir compte du fait que des étudiants voulant travailler ont souvent beaucoup de mal à cause de l'attitude mentionnée dans le document: "Manque de volonté de laisser un paresseux échouer et par la suite apprendre de ses propres erreurs". Ces étudiants doivent aussi apprendre à gérer le problème de mollasson/parasite. Bref, il n'y a pas beaucoup de victimes innocentes, au moins dans les cas que j'ai vus.

**Comment by fuhrmanator** [comment]
Exemple: Quelqu'un qui arrive chialer à l'enseignant à la fin de l'itération 2 et qui demande de changer d'équipe, mais cette personne n'a fait qu'absorber (verbe utiliser dans le texte) le mauvais comportement pendant 6 semaines. Elle doit aussi apprendre de cette erreur.

**Comment by yvanross** [comment]
Je vais demander à voir l'évaluation du plan d'itération ou ces problèmes devraient être identifié.  Donc pas nécessaire d'ajouter plus d'information dans le document d'exigence.
