### ISSUE TITLE
Nouveau CU de notification

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab1#54]
Notification par courriel et/ou SMS lorqu'il y a une exception.

**Comment by yvanross** [comment]
@fuhrmanator Qu'est ce que tu en pense? Ca pourrait être associé à la disponibilité!!

**Comment by fuhrmanator** [comment]
> Notification par courriel et/ou SMS lorqu'il y a une exception.

Je ne suis pas sûr de comprendre ce que tu entends par exception. Peux-tu donner un exemple? 

En général, c'est difficile dans les implémentations d'envoyer les SMS/Courriels sans un vrai système. Serait-il possible de valider?

**Comment by yvanross** [comment]
On peut laisser tomber cet idée.
