### ISSUE TITLE
Rappeler la planification d'activités (combien de temps relatifs prend chaque activité)

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-enonce-lab1#56]
Selon Larman, un plan d'itération prend moins d'une heure, les RDCU une demi-journée (à temps plein) et le codage... beaucoup de temps.
Une démo est moins d'une heure, cueillir les rétroactions pareille. On devrait rappeler ces aspects dans l'énoncé.

**Comment by yvanross** [comment]
voir section Déroulement des itérations et implémentation
