### ISSUE TITLE
Les gabarits de plan d'itération et de rapport n'existent plus

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-enonce-lab1#57]
Les gabarits ont été supprimés. 

- [Gabarit de plan d'itération](https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/rapports/plan-iteration-gabarit.md)
- [Gabarit de rapport](https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/rapports/RAPPORT-iteration-i.md)

On doit les garder.

**Comment by fuhrmanator** [comment]
@yvanross je suggère de faire des branches et un gros PR pour les changements pour l'automne pour mieux gérer ces choses.

**Comment by yvanross** [comment]
Ils sont toujours la dans rapports / gabarits

**Comment by fuhrmanator** [comment]
J'ai une erreur 404 https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/rapports/plan-iteration-gabarit.md

**Comment by yvanross** [comment]
A partir de quel endroit utilise tu ce lien...

**Comment by yvanross** [comment]
J'ai corrigé les liens

**Comment by fuhrmanator** [comment]
https://github.com/profcfuhrmanets/log210-enonce-lab1#gabarits mais je vois que c'est corrigé maintenant.

Dans mon tour des conseils pour Angular, j'ai trouvé https://angular.io/guide/styleguide#flat qui propose de garder une structure plate (flat) jusqu'à ce qu'on ait plus de 9-10 fichiers. Les deux gabarits pourraient bien aller dans la racine (rapports) comme avant. C'est une suggestion.
