### ISSUE TITLE
Imposer des Préalables pour les CU

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-enonce-lab1#6]
P.ex. ça ne fait pas de sens qu'une équipe implémente "corriger devoir" si le devoir n'a pas été créé ("gérer devoir").

**Comment by fuhrmanator** [comment]
Au moins, indiquer dans l'énoncé qu'une fonctionnalité (ex. corriger devoir) nécessitant une autre (ex. créer devoir) ne sera pas être acceptée.

**Comment by RubenLaden** [comment]
Il me semble qu'Yvan avait répondu à ce point dans le passé, disant que c'est la responsabilité des étudiants de choisir correctement leurs CUs :
[https://discord.com/channels/619589104019046406/620106057494298663/882668634797916221](url)
Si cette réponse est toujours d'actualité, on peut certainement fermer cette issue.
(Si le lien ne marche pas, je peux joindre une capture d'écran de sa réponse)
