### ISSUE TITLE
Ajouter un critère pour l'exigence « Vérification RDCU's » dans la grille de correction des rapports

### ISSUE THREAD

**Issue by elainesoucy** [profcfuhrmanets/log210-enonce-lab1#65]
![image](https://user-images.githubusercontent.com/46898201/159070033-02150f5c-8823-4bcb-ad2b-138f5eade76d.png)
Comme c'est sur 3 points, il faudrait ajuster les critères de la grille de correction. Il n'y a présentement que 0-1-2. Le critère 2 devrait être celui qui vaut 3 points.

**Comment by yvanross** [comment]
Voici les nouveaux critères.
0 - Aucune RDCU cohérentes avec les CU du plan ou utile pour faire le codage
1 - RDCU peu cohérentes avec les CU et partiellement utiles pour faire le codage
2 - RDCU cohérentes avec les CU mais incomplet donc peu utile pour faire le codage
3 - RDCU cohérentes avec les CU et utiles pour le codage

**Comment by fuhrmanator** [comment]
J'ai dû corriger les problèmes avec les indicateurs BCAPG qui étaient dans le rapport depuis que vous avez ajouté la section "Verification RDCU" - malheureusement, l'ajout de lignes dans les rapport brise le calcul des indicateurs. 

Je vous encourage toutes et tous de faire comme Élaine a fait - avant de changer la grille, vous faites une demande ici et on peut contrôler ce qui se passe. Sinon, je perds du temps à rétablir correctement les calculs du BCAPG qui sont très important (surtout à l'été).

Voici une capture d'écran de la version que j'ai actualisée:
![image](https://user-images.githubusercontent.com/7606540/168832199-1f4e536f-3ae7-4238-9bb2-59845f96c012.png)
