### ISSUE TITLE
4e test supplémentaire de *CU03a - Ajouter question* vérifie un élément non demandé dans les exigences

### ISSUE THREAD

**Issue by elainesoucy** [profcfuhrmanets/log210-enonce-lab1#73]
Pour le *CU03a - Ajouter devoir*, le test supplémentaire 4 vérifie que c'est impossible de créer un devoir avec un nom qui existe déjà. Par contre, le scénario alternatif précise plutôt qu'on doit vérifier que la date de début doit être avant la date de fin. Voici les exigences du CU03a :

![image](https://user-images.githubusercontent.com/46898201/173638397-98ae4e18-1a57-4309-a4bc-3b2f138a20d7.png)

Ainsi, je propose deux solutions pour palier à ce problème. 

1. Ajouter un cinquième test qui vérifiera que la date de début est avant la date de fin afin de tester le scénario alternatif. Cela fera en sorte quil faudra ajouter un scénario alternatif afin de vérifier que le nom d'un devoir doit être unique, car le test 4 le vérifie. 
2. Changer le quatrième test afin que celui-ci vérifie plutôt que la date de début doit être avant la date de fin.

**Comment by fuhrmanator** [comment]
Merci @elainesoucy - je suis en faveur de la 1ere solution. 

Il y a aussi un pb de français avec le 3e test.
