### ISSUE TITLE
Colonne « Vérification Conception » non nécessaire dans l'énoncé

### ISSUE THREAD

**Issue by elainesoucy** [profcfuhrmanets/log210-enonce-lab1#74]
La vérification de la conception est faite de façon interactive pendant la période. Je ne crois donc pas que la colonne « vérification conception » soit nécessaire. Nous ne regardons pas la version PDF du rapport, nous regardons certains artéfacts qu'ils nous montrent directement de leur ordinateur.

De plus, cela engendre une confusion pour l'itération 2 et 3, car il n'y a pas de correction interactive obligatoire des artéfacts comme à l'itération 1.

![image](https://user-images.githubusercontent.com/46898201/176179098-32bb4fde-b18d-4abe-b4e1-1a9617a94ede.png)

**Comment by fuhrmanator** [comment]
@yvanross qu'en penses-tu? 

@elainesoucy Je dirais que la vérification est tout de même importante pour les nouveaux CU, n'est-ce pas? Aussi, s'il y avait des pb de conception signalés à la première itération, on en fait le suivi?

Que faites-vous concrètement lors d'une telle vérification?

**Comment by elainesoucy** [comment]
On fait effectivement une vérification de la conception. Néanmoins, nous la faisons durant la période avec les étudiants. Nous ne téléchargeons pas les dossiers des équipes pour ce tag spécifique. Les étudiants nous montrent directement leurs artéfacts dans leur code en mode preview de .plantuml ou encore dans leur rapport s'ils l'ont mis à jour. Nous ne récupérons pas les dossiers avec les tags *rdcu1*, *rdcu2* ou *rdcu3*.
