### ISSUE TITLE
Ajout de plusieurs questions lors de la modification du questionnaire - CU05c

### ISSUE THREAD

**Issue by elainesoucy** [profcfuhrmanets/log210-enonce-lab1#75]
Pour le CU05c - Modifier questionnaire, le point 4 des exigences mentionne l'ajout d'une question. Cela ne pourrait-il pas être plusieurs questions que l'on veut ajouter ?
![image](https://user-images.githubusercontent.com/46898201/176216551-43f53199-5370-4d3c-8ed4-15a2dd78319d.png)

**Comment by fuhrmanator** [comment]
Oui - on peut changer le texte à _une ou plusieurs questions de la banque_

**Comment by fuhrmanator** [comment]
Point soulevé par un étudiant:

> Au point 3 du même CU, se peut-il qu'il y a une petite contradiction avec le test supp 2? Ça dit qu'on peut seulement modifier la description et/ou l'état et ensuite il faut tester si on modifie le nom avec un nom déjà existant. Est-ce qu'on doit faire le test?

> 
![image](https://user-images.githubusercontent.com/7606540/177341422-13bfff72-4c69-461a-a143-863c6255afed.png)
