### ISSUE TITLE
Incohérence d'un test supplémentaire du CU03c

### ISSUE THREAD

**Issue by francisETS** [profcfuhrmanets/log210-enonce-lab1#78]
À la ligne suivante du document d'exigences client, on peut lire qu'il est question d'un `questionnaire`  alors que le cas d'utilisation (CU03c) traite de `devoir` :
https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/33f5208d1e8c46b470b0afb5e187795ecb5633dd/README-exigences-client.md?plain=1#L367
Je crois qu'une petite erreur s'est glissée et qu'il faudrait tout simplement remplacer 
` 1. Démontrer qu'il n'est pas possible de nommer un questionnaire avec un nom qui existe déjà. `
par
` 1. Démontrer qu'il n'est pas possible de nommer un devoir avec un nom qui existe déjà. `

**Comment by fuhrmanator** [comment]
Merci! C'est corrigé
