### ISSUE TITLE
Liens vers le SGB pointant vers le dépôt d'Yvan Ross

### ISSUE THREAD

**Issue by probitaille** [profcfuhrmanets/log210-enonce-lab1#84]
Certains liens vers le SGB (Système de gestion des bordereaux) pointent vers le [dépôt d'Yvan Ross](https://github.com/yvanross/log210-systeme-gestion-bordereau-node-express-ts). 

Il faudrait éliminer les dépendances aux dépôts d'Yvan au risque de perdre du code source important.

**Comment by fuhrmanator** [comment]
@yvanross Veux-tu transférer le dépôt à moi, ou préfères-tu que j'en fasse une fork ?

**Comment by fuhrmanator** [comment]
Je viens de faire une fork à https://github.com/profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts -- je mets à jour la documentation de l'énoncé à ce propos.

**Comment by fuhrmanator** [comment]
@probitaille veux-tu vérifier les liens?
