### ISSUE TITLE
Quelle est la couverture de test demandée aux étudiants

### ISSUE THREAD

**Issue by NicolasBeaulieu88** [profcfuhrmanets/log210-enonce-lab1#86]
Bonjour,

l'énoncé ne semble pas contenir d'indication sur la couverture demandée aux étudiants. Dans les recommandations d'implémentation, il est dit : "Assurez-vous d'avoir une très bonne couverture de test (mais une couverture de 100 % ne veut pas dire qu'il n'y a pas de bogues!)." mais rien de plus.

Aussi, comment devrions-nous pénaliser les étudiants qui n'ont pas de couverture de test ? Je sais que l'ancienne grille d'évaluation avait un emplacement pour ça, mais la nouvelle ne semble pas vérifier la couverture de test.

**Comment by fuhrmanator** [comment]
C'est mieux d'être spécifique. 

La ligne suivante n'est qu'une recommandation:

https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/47d337465de983cf66b23eca0f5ac67dde43b04a/README.md?plain=1#L262

Par contre, l'exigence **S1 Contrainte de développement : environnement de test** qui était facultative est devenue "obligatoire", ce qui implique que l'évaluation de la couverture est également obligatoire:

https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/47d337465de983cf66b23eca0f5ac67dde43b04a/README-exigences-client.md?plain=1#L821 

Je trouve l'histoire de couverture controversée. C'est bien d'avoir une bonne couverture, mais la différence entre aucun test est un test est énorme comparée à un test avec une couverture médiocre et un test avec 100% de couverture.

L'autre problème est que la couverture dépend vraiment du code que tu veux tester. Établir le chiffre minimal pour une couverture adéquate me semble arbitraire. Franchement, puisque LOG210 n'est pas un cours axé sur l'élaboration de tests (comme un cours sur la maintenance), je pense qu'on devrait laisser tomber carrément l'évaluation de la couverture. 

En pratique, j'ai vu l'utilisation de la couverture pour évaluer si une modification de test est une amélioration, mais c'est encore difficile de juger (car le code que tu testes évolue aussi).

**Comment by fuhrmanator** [comment]
fixed by #87
