### ISSUE TITLE
Plusieurs liens Google docs ne sont pas accessibles par les étudiants

### ISSUE THREAD

**Issue by NicolasBeaulieu88** [profcfuhrmanets/log210-enonce-lab1#88]
Certains étudiants n'ont pas de courriel etsmtl.net et ne peuvent pas accéder les liens comme
"comment planifier une itération"
"Comment estimer la taille d'une itération"

**Comment by fuhrmanator** [comment]
Merci pour l'issue @NicolasBeaulieu88
