### ISSUE TITLE
Dans le document des exigences, le lien vers la grille de pointage ne fonctionne pas

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-enonce-lab1#93]
Ça s'affiche ainsi : [Pour les auxiliaires d'enseignement: Grille de pointage des exigences][grilleglobale]

**Comment by fuhrmanator** [comment]
Pourrais-tu mettre le lien vers le document qui a le problème STP

**Comment by Olon11** [comment]
Le fichier : https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/README-exigences-client.md?plain=1#L7

Le lien : https://etsmtl365-my.sharepoint.com/personal/christopher_fuhrman_etsmtl_ca/_layouts/15/Doc.aspx?sourcedoc={88b6101f-80ee-44f9-a811-c230abdf651a}&action=embedview&wdAllowInteractivity=False&wdHideGridlines=True&wdHideHeaders=True&wdDownloadButton=True&wdInConfigurator=True&wdInConfigurator=True
